### ISSUE TITLE
Hausübung

### ISSUE THREAD

**Issue by Gunther23** [rstropek-teaching/real-time-game-quiz-4bhif-Gunther23#1]
Sehr geehrter Herr Professor!

Ist es möglich, meine Lösung erst nächste Woche zu bringen, weil ich den Aufwand für diese Übung unterschätzt habe.

Mit freundlichen Grüßen
Julian Günther, 4 BHIF

**Comment by rstropek** [comment]
Kein Problem. Versuche bis nächste Woche, an der Hausübung zu arbeiten. Es ist eine gute Übung für den Test.

lg,
Rainer Stropek.
